---
- name: Update grub
  ansible.builtin.lineinfile: 
    path: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX"
    line: 'GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"'
    state: present
  notify: make grub config
  ignore_errors: true
